---
version: 2.1
jobs:
  say-hello:
    parameters:
      role_arn:
        type: string
        description: ARN of the IAM Role to assume
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: Say hello
          command: echo Hello, World!
      - run:
          name: Debug Parameter Values
          command: |
            echo "role_arn: << parameters.role_arn >>"
workflows:
  say-hello-workflow:
    jobs:
      - say-hello:
          role_arn: asdfasdf
